#!/bin/sh

# wannetwork -- set up WAN networking
#
# Copyright (c) 2016 Afero, Inc. All rights reserved.

IFCONFIG=/sbin/ifconfig
ROUTE=/sbin/route
RDISC6=/usr/bin/rdisc6
IPV6CALC=/usr/bin/ipv6calc
CAT=/bin/cat
RM=/bin/rm
MV=/bin/mv
ECHO=/bin/echo
GREP=/bin/grep
SED=/bin/sed
AWK=/usr/bin/awk

INTERFACE=wwan0

RESOLV_CONF_WAN=/tmp/resolv.conf.wan
RESOLV_CONF_TMP=/tmp/resolv.conf.wan.tmp
RDISC_OUT=/tmp/rdisc_out

subnetv4()
{
	${ECHO} ${1} | ${AWK} 'BEGIN { conv[0]=0; conv[1]=128; conv[2]=192; conv[3]=224; conv[4]=240; conv[5]=248; conv[6]=252; conv[7]=254 } \
{ \
	sl=$1; \
	div=int(sl/8); \
	rem=sl%8; \
	if (div > 0) { \
		printf "255."; \
		if (div > 1) { \
			printf "255."; \
			if (div > 2) { \
				printf "255."; \
				if (div > 3) { \
					printf "255\n"; \
				} else { \
					printf "%d\n",conv[rem]; \
				} \
			} else { \
				printf "%d.0\n", conv[rem]; \
			} \
		} else { \
			printf "%d.0.0\n", conv[rem]; \
		} \
	} else { \
		printf "%d.0.0.0\n", conv[rem]; \
	} \
}'
}


set_up_ip_v4()
{
	if [ "x${1}x" != "xx" ] ; then
		local sn=$(subnetv4 ${2})
		${IFCONFIG} ${INTERFACE} ${1} netmask ${sn} -arp up
		res=$?
		if [ ${res} -ne "0" ] ; then
			return ${res}
		fi
		${ROUTE} add default gw ${1} metric 50 ${INTERFACE}
	fi
}

set_up_ip_v6()
{
	if [ "x${1}x" != "xx" ] ; then
		# set link local address of interface
		${IFCONFIG} ${INTERFACE} add ${1}/${2}

		# find the router
		${RDISC6} -1 -r1 ${INTERFACE} > ${RDISC_OUT}

		local PREFIX=`${CAT} ${RDISC_OUT} | ${GREP} Prefix | ${SED} 's/ Prefix *: //'`
		local ROUTER=`${CAT} ${RDISC_OUT} | ${GREP} from | ${SED} 's/ from //'`

		local SUBNET=`echo ${PREFIX} | ${SED} 's/.*\///'`

		local GLOBAL_PREFIX=`${IPV6CALC} --in ipv6addr --out ipv6addr --printprefix ${PREFIX}`
		local GLOBAL_SUFFIX=`${IPV6CALC} --in ipv6addr --out ipv6addr --printsuffix ${1}/${SUBNET}`

		local GLOBAL_ADDR=${GLOBAL_PREFIX}:${GLOBAL_SUFFIX}

		# Set the global IP address
		${IFCONFIG} ${INTERFACE} add ${GLOBAL_ADDR}/${SUBNET}

		# Add the default route
		${ROUTE} -A inet6 add default gw ${ROUTER} metric 50 ${INTERFACE}
	fi
}

add_dns()
{
	if [ "x${2}x" != "xx" ] ; then
		${ECHO} "nameserver " ${2} >> ${1}
	fi
}

usage()
{
	${ECHO} "usage -- wannetwork up|down <ip_v4> <subnet_v4> <dns1_v4> <dns2_v4> <ip_v6> <subnet_v6> <dns1_v6> <dns2_v6>"
}

case $1 in
	up)
		${RM} -f ${RESOLV_CONF_WAN}
		${IFCONFIG} ${INTERFACE} up

		set_up_ip_v4 "${2}" "${3}"
		set_up_ip_v6 "${6}" "${7}"

		${RM} -f ${RESOLV_CONF_TMP}
		add_dns ${RESOLV_CONF_TMP} "$4"
		add_dns ${RESOLV_CONF_TMP} "$5"
		add_dns ${RESOLV_CONF_TMP} "$8"
		add_dns ${RESOLV_CONF_TMP} "$9"
		${MV} ${RESOLV_CONF_TMP} ${RESOLV_CONF_WAN}
		;;

	down)
		${IFCONFIG} ${INTERFACE} down
		${RM} -f ${RESOLV_CONF_WAN}
		;;

	*)
		usage
		;;
esac
